inherit_from:
  - .rubocop_todo.yml
  - https://relaxed.ruby.style/rubocop.yml

inherit_mode:
  merge:
    - Exclude

require: 
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: '2.7'
  UseCache: true
  CacheRootDirectory: ./.rubocop/cache
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'vendor/*'

